name: Umaku
favicon: null
layout_spectrum: 1
typography_spectrum: 0.72594
title: Umaku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1dded'
    - '#1d323f'
    - '#6e7e95'
    - '#000d15'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
