name: Umaku
favicon: null
layout_spectrum: 0.80913
typography_spectrum: 0.28511
title: Umaku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 1
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
