name: Umaku
favicon: null
layout_spectrum: 0.80913
typography_spectrum: 0.28511
title: Umaku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006790'
    - '#942440'
    - '#191919'
    - '#004080'
    - '#000080'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
