name: Umaku
favicon: null
layout_spectrum: 0.23131
typography_spectrum: 0.55057
title: Umaku
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d1dded'
    - '#1d323f'
    - '#6e7e95'
    - '#000d15'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
